   %% Clear memory and the command window
    clear;
    clc;
    
     %% Load eeglab
    [ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab;

 
    %% Initialize the ALLERP structure and CURRENTERP
    ALLERP     = buildERPstruct([]);
    CURRENTERP = 0;

 
    %% This defines the all variables
    %  200-300 ms time window, -200 to 0 ms baseline

    home_path    = pwd;
    subject_list_file = [home_path '/m21_subjlist_semant.csv'];
    interval   = [200 300];
    baseline    = [-200 0];
    bins         = 1:300;
    channels     = 1:27;
    output_fname = [home_path '/m21_mea_200300_200_sem.txt']
    format       = 'long'


ALLERP = pop_geterpvalues(subject_list_file, ...
                          interval,bins,channels , ...
                          'Baseline', baseline, ...
                          'Binlabel', 'on', ...
                          'FileFormat',format, ...
                          'Filename', output_fname, ...
                          'Fracreplace', 'NaN', ...
                          'InterpFactor',1, ...
                          'Measure', 'meanbl', ...
                          'Mlabel', 'mean_amp',...
                          'Resolution',3 );


    %% This defines the all variables 
    %  300 500 time window, -200 to 0 ms baseline
    home_path    = pwd;
    subject_list_file = [home_path '/m21_subjlist_semant.csv'];
    interval   = [300 500];
    baseline    = [-200 0];
    bins         = 1:300;
    channels     = 1:27;
    output_fname = [home_path '/m21_mea_300500_200_sem.txt']
    format       = 'long'


ALLERP = pop_geterpvalues(subject_list_file, ...
                          interval,bins,channels , ...
                          'Baseline', baseline, ...
                          'Binlabel', 'on', ...
                          'FileFormat',format, ...
                          'Filename', output_fname, ...
                          'Fracreplace', 'NaN', ...
                          'InterpFactor',1, ...
                          'Measure', 'meanbl', ...
                          'Mlabel', 'mean_amp',...
                          'Resolution',3 );

    %% This defines the all variables 
    %  200 300 time window, -150 to 50 ms baseline
    home_path    = pwd;
    subject_list_file = [home_path '/m21_subjlist_semant.csv'];
    interval   = [200 300];
    baseline    = [-150 50];
    bins         = 1:300;
    channels     = 1:27;
    output_fname = [home_path '/m21_mea_200300_150_sem.txt']
    format       = 'long'


ALLERP = pop_geterpvalues(subject_list_file, ...
                          interval,bins,channels , ...
                          'Baseline', baseline, ...
                          'Binlabel', 'on', ...
                          'FileFormat',format, ...
                          'Filename', output_fname, ...
                          'Fracreplace', 'NaN', ...
                          'InterpFactor',1, ...
                          'Measure', 'meanbl', ...
                          'Mlabel', 'mean_amp',...
                          'Resolution',3 );
                      
  %% This defines the all variables 
    %  300 500 time window, -150 to 50 ms baseline
    home_path    = pwd;
    subject_list_file = [home_path '/m21_subjlist_semant.csv'];
    interval   = [200 300];
    baseline    = [-150 50];
    bins         = 1:300;
    channels     = 1:27;
    output_fname = [home_path '/m21_mea_300500_150_sem.txt']
    format       = 'long'


ALLERP = pop_geterpvalues(subject_list_file, ...
                          interval,bins,channels , ...
                          'Baseline', baseline, ...
                          'Binlabel', 'on', ...
                          'FileFormat',format, ...
                          'Filename', output_fname, ...
                          'Fracreplace', 'NaN', ...
                          'InterpFactor',1, ...
                          'Measure', 'meanbl', ...
                          'Mlabel', 'mean_amp',...
                          'Resolution',3 );

    fprintf('\n\n\n**** FINISHED ****\n\n\n');  